### ISSUE TITLE
Adicionar transformação: Rotações

### ISSUE THREAD

**Issue by MatLegat** [victorfeijo/gtkmm_app#33]
3 tipos de rotações:
    Em torno do centro do mundo
    Em torno do centro do objeto
    Em torno de um ponto qualquer (arbitrário)‏

**Comment by victorfeijo** [comment]
Essas janelas de rotações podem ser feitas dentro da janela de list objects, fazendo que a list object fique um pouco mais complexa, com todas essas opções de transformações e rotações.
